/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CommandeRouteImport } from './routes/commande'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as NosBoutiquesRouteImport } from './routes/nos-boutiques'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as ProduitSlugRouteImport } from './routes/produit.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeRoute = CommandeRouteImport.update({
  id: '/commande',
  path: '/commande',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const NosBoutiquesRoute = NosBoutiquesRouteImport.update({
  id: '/nos-boutiques',
  path: '/nos-boutiques',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitSlugRoute = ProduitSlugRouteImport.update({
  id: '/produit/$slug',
  path: '/produit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRoute
  '/collections': typeof CollectionsRoute
  '/commande': typeof CommandeRoute
  '/contact': typeof ContactRoute
  '/nos-boutiques': typeof NosBoutiquesRoute
  '/panier': typeof PanierRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRoute
  '/collections': typeof CollectionsRoute
  '/commande': typeof CommandeRoute
  '/contact': typeof ContactRoute
  '/nos-boutiques': typeof NosBoutiquesRoute
  '/panier': typeof PanierRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRoute
  '/collections': typeof CollectionsRoute
  '/commande': typeof CommandeRoute
  '/contact': typeof ContactRoute
  '/nos-boutiques': typeof NosBoutiquesRoute
  '/panier': typeof PanierRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/boutique'
    | '/collections'
    | '/commande'
    | '/contact'
    | '/nos-boutiques'
    | '/panier'
    | '/produit/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/boutique'
    | '/collections'
    | '/commande'
    | '/contact'
    | '/nos-boutiques'
    | '/panier'
    | '/produit/$slug'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/boutique'
    | '/collections'
    | '/commande'
    | '/contact'
    | '/nos-boutiques'
    | '/panier'
    | '/produit/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  BoutiqueRoute: typeof BoutiqueRoute
  CollectionsRoute: typeof CollectionsRoute
  CommandeRoute: typeof CommandeRoute
  ContactRoute: typeof ContactRoute
  NosBoutiquesRoute: typeof NosBoutiquesRoute
  PanierRoute: typeof PanierRoute
  ProduitSlugRoute: typeof ProduitSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande': {
      id: '/commande'
      path: '/commande'
      fullPath: '/commande'
      preLoaderRoute: typeof CommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nos-boutiques': {
      id: '/nos-boutiques'
      path: '/nos-boutiques'
      fullPath: '/nos-boutiques'
      preLoaderRoute: typeof NosBoutiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$slug': {
      id: '/produit/$slug'
      path: '/produit/$slug'
      fullPath: '/produit/$slug'
      preLoaderRoute: typeof ProduitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  BoutiqueRoute: BoutiqueRoute,
  CollectionsRoute: CollectionsRoute,
  CommandeRoute: CommandeRoute,
  ContactRoute: ContactRoute,
  NosBoutiquesRoute: NosBoutiquesRoute,
  PanierRoute: PanierRoute,
  ProduitSlugRoute: ProduitSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
